apiVersion: v1

kind: Pod

metadata:

  name: nginx-pod-with-secret-volume

spec:

  containers:

  - name: nginx-container

    image: nginx:latest

    volumeMounts:

    - name: mysecretvolume

      mountPath: /etc/password-mounted-path

  volumes:

  - name: mysecretvolume
    secret:
      secretName: my-second-secret


