# ~/nginx-Pod-with-secret-env-variable.yaml

apiVersion: v1
kind: Pod

metadata:

  name: nginx-pod-with-secret-env-variable

  namespace: default

spec:

  containers:

   - name: nginx-container

     image: nginx:latest

     env:

     - name: PASSWORD_ENV_VAR # Name of env variable

       valueFrom:

         secretKeyRef:

           name: my-second-secret # Name of secret object

           key: db_password # Name of key in secret object
